#!/bin/sh

# Install package Locally for development(optional)
poetry export --without-hashes -f requirements.txt --output requirements.txt
pip install -r requirements.txt
pip install -e .

poetry install
poetry update
